### ISSUE TITLE
Access Denied after login on the Identity provider

### ISSUE THREAD

**Issue by yolepro** [gary-archer/oauth.mobilesample.ios#20]
I start the application without any change and it's loading correctly, but I have an Access Denied message when I am using the login / password given in the readme file. It seems to be a configuration problem on the Authorization Server side even if I have the login page showing I am correctly connected.
Could we have more information on the way you configured your Authorization Server (Root URL, Valid redirect URIs,...) to get such app working?

Thanks

**Comment by gary-archer** [comment]
Meant to say: my example is intentionally a little complex. If you want to get integrated with AppAuth libraries then this example that we produced at Curity might be easier to use. Eg you can more easily re-point it to your own authorization server:

- [GitHub Code Example](https://github.com/curityio/openid-client-ios-appauth)
- [Website Tutorial](https://curity.io/resources/learn/swift-ios-appauth/)

**Comment by yolepro** [comment]
Thank you for your feedback, I will have a look on your 2nd exemple. 
Nevertheless, I did the spa exemple which is working properly with the user credential you provide (guestuser@example.com), but the iOS example is not and I don't really understand why since I don't know exactly how your Authorization Server is configured. You give a link in your Blog on a [Cloud Authorization Server Setup](https://apisandclients.com/posts) Article, but it is unfortunately not refering the appropriate article.

**Comment by gary-archer** [comment]
It is a little difficult for me to understand your problem since the only info I have is that you received an Access Denied message. Could you maybe post a screenshot of it, so that I can see whether it is an application or authorization server error? Hopefully we can get you up and running.

In terms of the OAuth client settings in the authorization server, they look like this and the client ID is `2vshs4gidsbpnjmsprhh607ege`. I did some renaming recently so some images are currently a little incorrect and it will take me a little while to update them.

![OAuth settings](https://apisandclients.com/images/550/oauth-client2.jpg)

The [Cloud Authorization Server Setup](https://apisandclients.com/posts/managed-authorization-server-setup) is just base setup of claims etc so I don't think it will help you.

**Comment by gary-archer** [comment]
Ah - what is happening there is that associated domain registration has failed on your simulator. When [this JavaScript code](https://mobile.authsamples.com/basicmobileapp/oauth/callback) executes, the deep link is not invoked. Instead, the following URL runs in the browser - you get the same response if you go here in a desktop browser:

https://mobile.authsamples.com/basicmobileapp/oauth/callback

This domain only exists online to host deep linking asset files. It is a small CloudFront distribution, where CloudFront presents an access denied default error when non-existent resources are requested.

To fix your problem, I think you may need to activate Automatically Manage Signing in Xcode. Associated domain registration will hopefully then succeed. I have run the code sample like this on a simulator on a completely new computer in the past, when signed into a different Apple account to my own, so I think works alright.

I wrote some other notes on failures in [this blog post](https://apisandclients.com/posts/ios-code-sample-infrastructure), though how this works. Unfortunately, Apple do not make this stuff easy for us developers.

**Comment by wb7212** [comment]
@yolepro  were you able to resolve this issue? I have encountered the same problem.

**Comment by yolepro** [comment]
Hello @wb7212 unfortunately not. But from @gary-archer advice I went on the Curity code example which is working perfectly for me so I could use it as an example for my use cases.

**Comment by gary-archer** [comment]
I made a change then, to enable a working app, by switching to a private use URI scheme.
To do so, get the latest code and then follow [these instructions](https://github.com/gary-archer/oauth.mobilesample.ios/blob/master/README.md#deep-linking-registration-failures).

**Comment by wb7212** [comment]
@gary-archer Thanks, I was able to get it to work. @yolepro How did you implement the Curity code example? I am trying to SSO from Mobile App to Web.

**Comment by gary-archer** [comment]
SSO is based on cookies issued by identity systems. You should not usually need to write custom code.

**ANDROID**

If you log into my mobile app on an Android device, then open Chrome and browse to https://www.authsamples.com you will see an SSO event.

**iOS**

If you log into my mobile app on an iOS device, then open Safari and browse to https://www.authsamples.com you may see an SSO event.

**MAINSTREAM BEHAVIOUR**

When they do not have a token yet, apps can either redirect automatically or present a login button to the user, to keep them informed. Mine do the latter. SSO occurs when the identity systems do not provide a prompt on the second redirect.

**ADVANCED BEHAVIOR**

There are some nuances, which are described in the [Nonce Authenticator Pattern](https://curity.io/resources/learn/nonce-authenticator-pattern/) article. By default though, use the mainstream behaviour.

**Comment by gary-archer** [comment]
Out of interest, I did a bit more digging around on your failures, since I am interested in developer setups.\
There is a way to [get claimed HTTPS schemes working](https://github.com/gary-archer/oauth.mobilesample.ios/blob/master/DevelopmentWebServer/README.md) but it is pretty unpleasant.\
Anyway, I will close this issue, since at least now there are options to enable a working system.
