### ISSUE TITLE
Trying to capture authorisation code to log-in to back-end server

### ISSUE THREAD

**Issue by bottlehall** [gary-archer/oauth.mobilesample.ios#24]
This is my first time using OAuth, so I may be trying to do the wrong thing entirely.

I have configured the latest commit to use Microsoft Identity (Azure, Entra, etc.) and it gets as far as closing the browser having accepted my credentials the first time and 'Continue' for second and subsequent attempts. However, it never updates the view to show that it is logged-in. I have put breakpoints in everywhere I can think of and can't find any response to the App.

I have tried other apps, specifically tied to MSAL, but I would prefer to use this repo as it would seem to offer a broader range of services to be configured - assuming I get MSAL working first!

I would be very grateful for any help.

**Comment by gary-archer** [comment]
Mine is a tricky code sample due to its use of iOS universal links to receive the login response. I expect you are having problems returning to your app because of that.

**SIMPLER SOLUTION**

If you just want to login to Microsoft using AppAuth libraries, you might start with [this simpler code sample](https://curity.io/resources/learn/swift-ios-appauth/) that we provided at Curity:

- Run the app in Xcode
- Update [this configuration file](https://github.com/curityio/openid-client-ios-appauth/blob/main/config.json) with your Entra ID settings

**MORE COMPLEX SOLUTION**

If you really want to get logins working using universal links, [this page](https://apisandclients.com/posts/ios-code-sample-infrastructure) has some further info on how to make universal links work for development, though it is a little unpleasant.

**SECURITY LIBRARIES**

I tend to avoid vendor-specific libraries. Your app runs a code flow and users should then be able to authenticate in many ways, depending on what the authorization server supports. It's not that hard to manually implement a code flow.

**Comment by bottlehall** [comment]
Thank you very much for your detailed reply. I will work through your suggestions and get back to you.

**Comment by bottlehall** [comment]
I am grateful for both your apps as they have taught me a huge amount about the subject that I wouldn't have gained so quickly in other ways.
